name: CI

on:
    - push
    - pull_request
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ghdl/setup-ghdl-ci@nightly
    - run: bash test.sh

